### ISSUE TITLE
Provide links for awesome-go

### ISSUE THREAD

**Issue by lieff** [tosone/minimp3#1]
https://github.com/avelino/awesome-go/pull/1785
https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md
awesome-go requires godoc.org, goreportcard.com and coverage links to be listed.

**Comment by tosone** [comment]
OK. I will add test for this. Thank you.

**Comment by lieff** [comment]
Thanks :)
