### ISSUE TITLE
Player adjustment time and sound problems.

### ISSUE THREAD

**Issue by HeyDon-Lee** [tosone/minimp3#13]
Do you support resizing sound? 
Do you support adjusting playback time?

**Comment by tosone** [comment]
Your mean that resample raw audio and specified a time to skip to play?

**Comment by HeyDon-Lee** [comment]
yes

**Comment by tosone** [comment]
No, this repo just support decode mp3 data to raw data. You can do it by yourself base on mp3's bitrate and sample size, calculate the size that you should be skipped.

By the way i am working on another repo [goff](https://github.com/miniav/goff) to binding FFmpeg, can be help this, but not complete.
