### ISSUE TITLE
Wrong EOF behavior

### ISSUE THREAD

**Issue by olup** [tosone/minimp3#18]
Don't you get an EOF error when caling decoder.Read() faster or with larger buffer than the speed of decoding itself - even if you haven't actually decoded the whole file ?

**Comment by tosone** [comment]
No, never got this error.

``` go
var dec *minimp3.Decoder
if dec, err = minimp3.NewDecoder(file); err != nil {
    log.Fatal(err)
}
started := dec.Started()
<-started
```

perhaps, you can wait for the first frame decoded, and read the raw radio.

If the read is slow than the decoder, the decoder will be stopped till the channel buffer is lower than 10240 bytes(10kib).

**Comment by tosone** [comment]
Can you give me some code to reproduce this issue?

**Comment by olup** [comment]
I'll try to ost an example. But in effect I have the same initialization code as you posted, then loop with a décider.read() to a buffer of 1024, then write the buffer to another audio encoder.

I frequently get EOF even when the file is not completely decoded. Looking at the implementation it seems EOF is triggered when we reach the end of decoded data without knowledge if the decoding is complete

**Comment by olup** [comment]
The `Read()`function returns EOF when`decodedData` is empty here https://github.com/tosone/minimp3/blob/d22286f16ad828a2b321ac1d6900fd255a60404f/decode.go#L157

However, the decoded data buffer can be empty before the end of the file decoding, for instance in the 10ms gap of waiting for the reading buffer to be filled, plus the time the decoding will take. It's entirely possible to read all the decoded data, meet EOF, but without having finishing reading the file.

This is my for loop for reading and encoding (encoder is a go-lame encoder - I am re-encoding mp3s into a specific configuration):
```
	for {
		n, err := decoder.Read(buffer)
		if err != nil {
			if err == io.EOF {
					break
				}
			return err
		}

		_, err = encoder.Write(buffer[:n])
		if err != nil {
			return err
		}
	}
```
This will return EOF before finishing reading the file. It gets better if I add some delay in the loop, but is highly inefficient. I also used a pattern where I retry x times after geting eof with some delay before retrying, this works very well but is completely hacky. Couldn't go-minimp3 return EOF only if the file is completely decoded and an error like `endOfBuffer` when we only reached the end of decodedData but have more to read on the file?

**Comment by tosone** [comment]
I see it, let me try to fix it.
> Couldn't go-minimp3 return EOF only if the file is completely decoded and an error like endOfBuffer when we only reached the end of decodedData but have more to read on the file?

**Comment by tosone** [comment]
#19 I think this pr should fix this. Could please try this?

**Comment by olup** [comment]
Great, works very well :-)

**Comment by tosone** [comment]
A new tag has been released. https://github.com/tosone/minimp3/releases/tag/v1.0.2 ^_^
