### ISSUE TITLE
can this library be used for playing any mp3 files?

### ISSUE THREAD

**Issue by hitzhangjie** [tosone/minimp3#2]
I test this library with a downloaded mp3 file, it cannot play music clearly. But it can play your test.mp3, so I want to ask, does this library can be used for playing any mp3 file?

I checked the downloaded file, its rate is 44100, channel is 2.

**Comment by tosone** [comment]
Yes, it can play every kind of mp3 music.
My device was using it play mp3 network audio and works well. :smile:

**Comment by lieff** [comment]
Probably insufficient buffer problem, 16kb is recommended. If it's not, can you share problem file? I can take a look.

**Comment by tosone** [comment]
Now we can test like this:

``` bash
cd example/networkAudio && make && make test
```
