### ISSUE TITLE
Native Mp3 Encoding for Go ?

### ISSUE THREAD

**Issue by c0ze** [tosone/minimp3#4]
Sorry this is not really an issue, but just a question.

Does anyone know a native mp3 encoding lib for Go ?

**Comment by lieff** [comment]
https://github.com/hajimehoshi/go-mp3

**Comment by c0ze** [comment]
thank you, but it seems only to decode.

I am looking for an encoder, which will take raw audio / wav and encode into mp3.

**Comment by lieff** [comment]
For encoder I know only wrappers:
https://github.com/viert/lame
https://github.com/sunicy/go-lame

lame is best encoder, ant it's lot of work to port it.
Second best is shine encoder and same problem.

**Comment by c0ze** [comment]
Thank you ! I think lame is good, I opened an issue for my use case,

https://github.com/sunicy/go-lame/issues/1
