### ISSUE TITLE
MP3 Duration

### ISSUE THREAD

**Issue by guilhermehubner** [tosone/minimp3#9]
Is it possible to get the duration ?

**Comment by lieff** [comment]
In general case all file must be parsed to calculate the duration.
You can use mp3dec_iterate/mp3dec_iterate_buf to iterate through all frames and analyse headers using hdr_frame_samples().
Even in this case fast parser method can produce slightly incorrect result in case if not all frames are decodable (this is normal situation for cut`ed mp3's with not decodable start frame(s)).
But if we know that mp3 file is CBR, all frames are decodable and no padding - then duration calculation is trivial. Then we only need to analyse first frame, calc nframes=file_size/first_frame_size, calc samples=nframes*hdr_frame_samples(first_header) and calc duration from samples.
